version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  backend-test:
    working_directory: ~/crud-application/backend
    docker:
      - image: circleci/node:12
    steps:
      - checkout:
          path: ~/crud-application
      - attach_workspace:
          at: ~/crud-application
      - run:
          name: Install Dependencies
          command: cd backend; yarn install
      - run:
          name: Run tests
          command: cd backend; yarn run test
      - run:
          command: yarn run test
workflows:
  testing:
    jobs:
      - backend-test
