version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  backend-test:
    working_directory: ~/crud-application/backend
    docker:
      - image: circleci/node:12
    steps:
      - run:
          name: Linux update
          command: |
            sudo apt-get update 
            sudo apt-get install -y lsb-release libudev-dev libusb-dev usbutils
            sudo apt-get clean all
            lsb_release -a
      - checkout:
          path: ~/crud-application
      - attach_workspace:
          at: ~/crud-application
      - run:
          name: Install Dependencies
          command: cd backend; yarn install
      - run:
          name: Run tests
          command: cd backend; yarn run test
      - run:
          command: yarn run test
workflows:
  testing:
    jobs:
      - backend-test
