version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-n-test-backend:
    working_directory: ~/crud-application/backend
    executor:
      name: node/default
      tag: '12'
    steps:
      - checkout:
          path: ~/crud-application
      - node/install-packages:
          app-dir: ~/crud-application/backend
          pkg-manager: yarn
      - run:
          command: yarn run test
workflows:
  build-n-test:
    jobs:
      - build-n-test-backend